services:
  proxy-router:
    build:
      args:
        - PYTHON_VERSION=3.11
      context: .
      dockerfile: ./Dockerfile
    container_name: proxy-router
    environment:
      - AUTH_CONFIG_FILE_PATH=/app/auth.json
      - LOGGING_LEVEL=INFO
      - PROXY_ROUTING_CONFIG_FILE_PATH=/app/proxy.json
      - PROXY_SERVER_BUFFER_SIZE_BYTES=4096
      - PROXY_SERVER_HOST=0.0.0.0
      - PROXY_SERVER_PORT=8888
      - PROXY_SERVER_TIMEOUT_SECONDS=2.0
      - ROUTING_CONFIG_FILE_PATH=/app/routing.json
    image: proxy-router:latest
    ports:
      - "8888:8888"
    restart: unless-stopped
    volumes:
      - ./secrets/auth.json:/app/auth.json
      - ./secrets/proxy.json:/app/proxy.json
      - ./secrets/routing.json:/app/routing.json
