services:
  proxy-router:
    build:
      args:
        - DOCKER_REGISTRY_MIRROR=${DOCKER_REGISTRY_MIRROR}
        - PYTHON_VERSION=3.11
      context: .
      dockerfile: ./Dockerfile
      secrets:
        - pip_index_url
        - pip_proxy
        - pip_trusted_host
    container_name: proxy-router
    environment:
      - BASIC_AUTH_USER=${AUTH_USER}
      - BASIC_AUTH_PASSWORD=${AUTH_PASSWORD}
      - LOGGING_LEVEL=INFO
      - PROXY_ROUTING_CONFIG_FILE_PATH=/app/routing.json
      - PROXY_SERVER_BUFFER_SIZE_BYTES=4096
      - PROXY_SERVER_HOST=0.0.0.0
      - PROXY_SERVER_PORT=8888
      - PROXY_SERVER_TIMEOUT_SECONDS=2.0
    image: proxy-router:latest
    ports:
      - "8888:8888"
    restart: unless-stopped
    volumes:
      - ./secrets/routing.json:/app/routing.json  # Modify this with your routing rules
secrets:
  pip_index_url:
    environment: PIP_INDEX_URL
  pip_proxy:
    environment: PIP_PROXY
  pip_trusted_host:
    environment: PIP_TRUSTED_HOST
